#include "bsp_delay.h"

/* TIM2 handle generated by CubeMX (defined in tim.c) */
extern TIM_HandleTypeDef htim2;

/**
 * @brief  Start TIM2 as a free-running microsecond counter.
 */
void bsp_delay_init(void)
{
    HAL_TIM_Base_Start(&htim2);
}

/**
 * @brief  Microsecond delay using TIM2 counter.
 * @param  us: delay in microseconds.
 * @note   The counter is reset to 0 first, then we poll CNT until it
 *         reaches the target value. Since TIM2 runs at 1MHz, one tick
 *         equals exactly one microsecond.
 */
void bsp_delay_us(uint32_t us)
{
    uint32_t start = __HAL_TIM_GET_COUNTER(&htim2);

    while ((uint32_t)(__HAL_TIM_GET_COUNTER(&htim2) - start) < us)
    {
        /* busy wait */
    }
}

/**
 * @brief  Millisecond delay.
 * @param  ms: delay in milliseconds.
 */
void bsp_delay_ms(uint32_t ms)
{
    while (ms--)
    {
        bsp_delay_us(1000);
    }
}
