/**
  ******************************************************************************
  * @file    bsp_delay.c
  * @brief   Implementation of the board delay layer.
  * @note    TIM2 is started once in BSP_Delay_Init() and then free runs. Every delay
  *          only samples CNT and waits until the difference reaches the wanted value,
  *          so no interrupt and no extra timer is needed.
  ******************************************************************************
  */
#include "bsp_delay.h"

/* TIM2 handle generated by CubeMX (defined in main.c) */
extern TIM_HandleTypeDef htim2;

/**
 * @brief  Start TIM2 as a free-running microsecond counter.
 */
void BSP_Delay_Init(void)
{
    HAL_TIM_Base_Start(&htim2);
}

/**
 * @brief  Microsecond delay using TIM2 counter.
 * @param  us: delay in microseconds.
 * @note   The counter is sampled first, then we poll CNT until the target
 *         value is reached. Since TIM2 runs at 1MHz, one tick equals
 *         exactly one microsecond.
 */
void BSP_Delay_Us(uint32_t us)
{
    uint32_t start = __HAL_TIM_GET_COUNTER(&htim2);

    while ((uint32_t)(__HAL_TIM_GET_COUNTER(&htim2) - start) < us)
    {
        /* busy wait */
    }
}

/**
 * @brief  Millisecond delay.
 * @param  ms: delay in milliseconds.
 */
void BSP_Delay_Ms(uint32_t ms)
{
    while (ms--)
    {
        BSP_Delay_Us(1000);
    }
}
