#include "bsp_uart.h"

/* USART1 handle generated by CubeMX (defined in usart.c) */
extern UART_HandleTypeDef huart1;

/**
 * @brief  Redirect printf to USART1.
 * @param  ch: character to send.
 * @param  f:  file stream (unused).
 * @retval ch write a char on success, -1 on failure.
 * @note   "Use MicroLIB" must be checked in Keil (Options -> Target).
 */
int fputc(int ch, FILE *f)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/**
 * @brief  Reserved for future UART features (e.g. DMA, ring buffer).
 */
void bsp_uart_init(void)
{
    /* Nothing to do for now */
}
