/**
  ******************************************************************************
  * @file    bsp_uart.c
  * @brief   Implementation of the board UART layer.
  * @note    USART2 reception is a DMA ring plus the IDLE interrupt. HAL is kept out
  *          of the receive path on purpose: HAL_UART_Receive_DMA() aborts reception on
  *          the first overrun or framing error, which would silently kill the link
  *          until the next reset.
  ******************************************************************************
  */
#include "bsp_uart.h"
#include <string.h>

/* USART1 (console) and USART2 (gateway) handles are generated by CubeMX and
   defined in main.c. */
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart2;
extern DMA_HandleTypeDef  hdma_usart2_rx;

#ifdef BSP_UART_DEBUG
volatile uint32_t g_bsp_rx_bytes;
volatile uint32_t g_bsp_rx_drop;
volatile uint32_t g_bsp_idle_evt;
volatile uint32_t g_bsp_uart_err;
#endif

static uint8_t  s_rx_buf[BSP_UART2_RX_BUF_SIZE];  /* filled by the DMA, wraps */
static uint16_t s_rx_tail;                        /* oldest byte still unread */
static volatile uint8_t s_rx_idle;                /* set by the IDLE interrupt */

/**
 * @brief  Redirect printf to USART1.
 * @param  ch: character to send.
 * @param  f:  file stream (unused).
 * @retval ch write a char on success, -1 on failure.
 * @note   "Use MicroLIB" must be checked in Keil (Options -> Target).
 */
int fputc(int ch, FILE *f)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}

/**
 * @brief  Bring up the debug console.
 */
void BSP_Uart_Init(void)
{
    /* USART1 is fully configured by CubeMX (MX_USART1_UART_Init). */
}

/**
 * @brief  Arm the DMA ring and the IDLE interrupt of USART2.
 */
void BSP_Uart2_Init(void)
{
    __HAL_DMA_DISABLE(&hdma_usart2_rx);
    hdma_usart2_rx.Instance->CPAR  = (uint32_t)&huart2.Instance->DR;
    hdma_usart2_rx.Instance->CMAR  = (uint32_t)s_rx_buf;
    hdma_usart2_rx.Instance->CNDTR = (uint32_t)BSP_UART2_RX_BUF_SIZE;
    s_rx_tail = 0U;
    __HAL_DMA_ENABLE(&hdma_usart2_rx);
    SET_BIT(huart2.Instance->CR3, USART_CR3_DMAR);   /* UART asks the DMA     */
    __HAL_UART_CLEAR_IDLEFLAG(&huart2);              /* needs an SR + DR read */
    SET_BIT(huart2.Instance->CR1, USART_CR1_IDLEIE);
}

/**
 * @brief  Copy the bytes that arrived since the last call out of the ring.
 * @param  dst: destination buffer.
 * @param  max: capacity of the destination buffer.
 * @retval number of bytes copied, 0 when nothing is pending.
 */
uint16_t BSP_Uart2_RxTake(uint8_t *dst, uint16_t max)
{
    uint16_t head = (uint16_t)(BSP_UART2_RX_BUF_SIZE - (uint16_t)__HAL_DMA_GET_COUNTER(&hdma_usart2_rx));
    uint16_t n;
    uint16_t first;

    if (head == s_rx_tail)
    {
        return 0U;
    }
    n = (head > s_rx_tail) ? (uint16_t)(head - s_rx_tail)
                           : (uint16_t)(BSP_UART2_RX_BUF_SIZE - s_rx_tail + head);
    if (n > max)
    {
        /* The poll came too late: keep the newest bytes, drop the oldest ones. */
#ifdef BSP_UART_DEBUG
        g_bsp_rx_drop += (uint32_t)(n - max);
#endif
        s_rx_tail = (uint16_t)((head + BSP_UART2_RX_BUF_SIZE - max) % BSP_UART2_RX_BUF_SIZE);
        n = max;
    }
    if ((uint16_t)(s_rx_tail + n) <= BSP_UART2_RX_BUF_SIZE)
    {
        memcpy(dst, &s_rx_buf[s_rx_tail], n);
    }
    else
    {
        first = (uint16_t)(BSP_UART2_RX_BUF_SIZE - s_rx_tail);
        memcpy(dst, &s_rx_buf[s_rx_tail], first);
        memcpy(&dst[first], &s_rx_buf[0], (uint16_t)(n - first));
    }
    s_rx_tail = (uint16_t)((s_rx_tail + n) % BSP_UART2_RX_BUF_SIZE);
#ifdef BSP_UART_DEBUG
    g_bsp_rx_bytes += (uint32_t)n;
#endif
    return n;
}

/**
 * @brief  Tell whether the line went idle since the last call.
 * @retval 1 when an idle event is pending, 0 otherwise.
 */
uint8_t BSP_Uart2_IdleTake(void)
{
    if (s_rx_idle == 0U)
    {
        return 0U;
    }
    s_rx_idle = 0U;
    return 1U;
}

/**
 * @brief  Blocking transmit on USART2.
 * @param  data: bytes to send.
 * @param  len:  number of bytes to send.
 * @retval 0 on success, 1 on failure.
 */
uint8_t BSP_Uart2_Tx(const uint8_t *data, uint16_t len)
{
    return (HAL_UART_Transmit(&huart2, (uint8_t *)data, len, BSP_UART2_TX_TIMEOUT_MS) == HAL_OK)
           ? 0U : 1U;
}

/**
 * @brief  USART2 interrupt hook, called first inside USART2_IRQHandler().
 */
void BSP_Uart2_IrqHandler(void)
{
    uint32_t sr = huart2.Instance->SR;

#ifdef BSP_UART_DEBUG
    if ((sr & (USART_SR_ORE | USART_SR_NE | USART_SR_FE | USART_SR_PE)) != 0U)
    {
        g_bsp_uart_err++;                         /* cleared by the DR read below */
    }
#endif
    if ((sr & USART_SR_IDLE) != 0U)
    {
        (void)huart2.Instance->DR;                /* SR + DR read clears IDLE */
        s_rx_idle = 1U;
#ifdef BSP_UART_DEBUG
        g_bsp_idle_evt++;
#endif
    }
}
