#include "bsp_link.h"
#include "bsp_uart.h"                 /* debug prints go to USART1 */
#include <string.h>
#include <stdio.h>

/* USART2 and its RX DMA channel are generated by CubeMX and defined in main.c. */
extern UART_HandleTypeDef huart2;
extern DMA_HandleTypeDef  hdma_usart2_rx;

#define LINK_RX_CHUNK   64U           /* bytes copied out of the ring per pass */

/* --------------------------------------------------------------------------
 * Debug counters: plain globals, compiled out together with LINK_DEBUG.
 * -------------------------------------------------------------------------- */
#ifdef LINK_DEBUG
volatile uint32_t g_link_rx_bytes;
volatile uint32_t g_link_rx_drop;
volatile uint32_t g_link_idle_evt;
volatile uint32_t g_link_uart_err;
volatile uint32_t g_link_frame_ok;
volatile uint32_t g_link_frame_bad;
volatile uint32_t g_link_frame_other;
volatile uint32_t g_link_cmd_rx;
volatile uint32_t g_link_ack_tx;
volatile uint32_t g_link_nak_tx;
volatile uint32_t g_link_ack_rx;
volatile uint32_t g_link_nak_rx;
volatile uint32_t g_link_retry_tx;
volatile uint32_t g_link_timeout_tx;
#endif

/* -------------------------------- reception -------------------------------- */
static uint8_t  s_rx_buf[LINK_RX_BUF_SIZE];      /*  filled by the DMA, wraps  */
static uint16_t s_rx_tail;                       /*  oldest byte still unread  */
static volatile uint8_t s_rx_idle;               /*  set by the IDLE interrupt */

static uint8_t  s_asm_buf[LINK_MAX_FRAME * 2U];  /* frames being reassembled   */
static uint16_t s_asm_len;

/* -------------------------------- transmit --------------------------------- */
static uint8_t  s_tx_frame[LINK_MAX_FRAME];
static uint8_t  s_report_payload[LINK_MAX_PAYLOAD];
static uint8_t  s_tx_seq;                        /* global sequence number     */

/* ---------------- one acknowledged transaction (stop and wait) ------------- */
static uint8_t  s_tx_pend;                       /* 1 = waiting for one answer */
static uint8_t  s_tx_pend_cmd;
static uint8_t  s_tx_pend_seq;
static uint8_t  s_tx_pend_payload[LINK_MAX_PAYLOAD];
static uint8_t  s_tx_pend_len;
static uint8_t  s_tx_retry;
static uint32_t s_tx_deadline;
static uint8_t  s_tx_failed;                     /* 1 = last transaction failed */

static Link_CmdHandler_t s_cmd_handler;

/**
 * @brief  CRC16/MODBUS checksum, polynomial 0xA001, initial value 0xFFFF.
 * @param  data: input buffer.
 * @param  len:  input length in bytes.
 * @retval 16-bit checksum.
 */
static uint16_t Link_Crc16(const uint8_t *data, uint16_t len)
{
    uint16_t crc = 0xFFFFU;
    uint16_t i;
    uint8_t  bit;
    for (i = 0U; i < len; i++)
    {
        crc ^= data[i];
        for (bit = 0U; bit < 8U; bit++)
        {
            crc = ((crc & 0x0001U) != 0U) ? (uint16_t)((crc >> 1) ^ 0xA001U) : (uint16_t)(crc >> 1);
        }
    }
    return crc;
}

/**
 * @brief  Arm the DMA ring and the IDLE interrupt of USART2.
 * @note   CubeMX already configured DMA1_Channel6 as byte/circular/incrementing,
 *         so only the pointers and the enable bits are programmed here.
 *         HAL is deliberately kept out of the receive path: HAL_UART_Receive_DMA()
 *         aborts reception on the first overrun or framing error, which would
 *         silently kill the link until the next reset.
 */
static void Link_RxStart(void)
{
    __HAL_DMA_DISABLE(&hdma_usart2_rx);
    hdma_usart2_rx.Instance->CPAR  = (uint32_t)&huart2.Instance->DR;
    hdma_usart2_rx.Instance->CMAR  = (uint32_t)s_rx_buf;
    hdma_usart2_rx.Instance->CNDTR = (uint32_t)LINK_RX_BUF_SIZE;
    s_rx_tail = 0U;
    __HAL_DMA_ENABLE(&hdma_usart2_rx);
    SET_BIT(huart2.Instance->CR3, USART_CR3_DMAR);   /* UART asks the DMA     */
    __HAL_UART_CLEAR_IDLEFLAG(&huart2);              /* needs an SR + DR read */
    SET_BIT(huart2.Instance->CR1, USART_CR1_IDLEIE);
}

/**
 * @brief  Copy the bytes that arrived since the last call out of the ring.
 * @param  dst: destination buffer.
 * @param  max: capacity of the destination buffer.
 * @retval number of bytes copied, 0 when nothing is pending.
 */
static uint16_t Link_RxTake(uint8_t *dst, uint16_t max)
{
    uint16_t head = (uint16_t)(LINK_RX_BUF_SIZE - (uint16_t)__HAL_DMA_GET_COUNTER(&hdma_usart2_rx));
    uint16_t n;
    uint16_t first;

    if (head == s_rx_tail)
    {
        return 0U;
    }
    n = (head > s_rx_tail) ? (uint16_t)(head - s_rx_tail)
                           : (uint16_t)(LINK_RX_BUF_SIZE - s_rx_tail + head);
    if (n > max)
    {
        /* The poll came too late: keep the newest bytes, drop the oldest ones. */
#ifdef LINK_DEBUG
        g_link_rx_drop += (uint32_t)(n - max);
#endif
        s_rx_tail = (uint16_t)((head + LINK_RX_BUF_SIZE - max) % LINK_RX_BUF_SIZE);
        n = max;
    }
    if ((uint16_t)(s_rx_tail + n) <= LINK_RX_BUF_SIZE)
    {
        memcpy(dst, &s_rx_buf[s_rx_tail], n);
    }
    else
    {
        first = (uint16_t)(LINK_RX_BUF_SIZE - s_rx_tail);
        memcpy(dst, &s_rx_buf[s_rx_tail], first);
        memcpy(&dst[first], &s_rx_buf[0], (uint16_t)(n - first));
    }
    s_rx_tail = (uint16_t)((s_rx_tail + n) % LINK_RX_BUF_SIZE);
#ifdef LINK_DEBUG
    g_link_rx_bytes += (uint32_t)n;
#endif
    return n;
}

/**
 * @brief  Build one frame and push it out of USART2.
 * @param  cmd:         command code.
 * @param  seq:         sequence number to put into the frame.
 * @param  payload:     payload bytes, may be NULL when payload_len is 0.
 * @param  payload_len: payload length in bytes.
 * @retval LINK_RET_OK or LINK_RET_FAIL.
 */
static uint8_t Link_SendFrame(uint8_t cmd, uint8_t seq, const uint8_t *payload, uint8_t payload_len)
{
    uint16_t crc;
    uint16_t total;

    if (payload_len > LINK_MAX_PAYLOAD)
    {
        return LINK_RET_FAIL;
    }
    if ((payload_len > 0U) && (payload == NULL))
    {
        return LINK_RET_FAIL;
    }
    s_tx_frame[0] = LINK_SOF0;
    s_tx_frame[1] = LINK_SOF1;
    s_tx_frame[LINK_OFF_VER] = LINK_VER;
    s_tx_frame[LINK_OFF_ADDR] = LINK_ADDR_LOCAL;
    s_tx_frame[LINK_OFF_LEN] = payload_len;
    s_tx_frame[LINK_OFF_CMD] = cmd;
    s_tx_frame[LINK_OFF_SEQ] = seq;
    if (payload_len > 0U)
    {
        memcpy(&s_tx_frame[LINK_OFF_PAYLOAD], payload, payload_len);
    }
    crc = Link_Crc16(&s_tx_frame[LINK_OFF_VER],
                     (uint16_t)((LINK_HDR_LEN - LINK_OFF_VER) + payload_len));
    total = (uint16_t)(LINK_HDR_LEN + payload_len);
    s_tx_frame[total] = (uint8_t)(crc & 0x00FFU);
    total++;
    s_tx_frame[total] = (uint8_t)((crc >> 8) & 0x00FFU);
    total++;
    return (HAL_UART_Transmit(&huart2, s_tx_frame, total, LINK_UART_TIMEOUT_MS) == HAL_OK)
           ? LINK_RET_OK : LINK_RET_FAIL;
}

/**
 * @brief  Answer one command with ACK (reason == LINK_OK) or with NAK.
 * @param  seq:    sequence number of the command being answered.
 * @param  cmd:    command code being answered.
 * @param  reason: LINK_OK or a LINK_NAK_xxx code.
 */
static void Link_SendAnswer(uint8_t seq, uint8_t cmd, uint8_t reason)
{
    uint8_t payload[2];

    payload[0] = cmd;
    if (reason == LINK_OK)
    {
        (void)Link_SendFrame(LINK_CMD_ACK, seq, payload, 1U);
#ifdef LINK_DEBUG
        g_link_ack_tx++;
#endif
    }
    else
    {
        payload[1] = reason;
        (void)Link_SendFrame(LINK_CMD_NAK, seq, payload, 2U);
#ifdef LINK_DEBUG
        g_link_nak_tx++;
#endif
    }
}

/**
 * @brief  Hand one complete and CRC-checked frame to the command layer.
 * @param  frame: the whole frame, starting with 0xAA 0x55.
 */
static void Link_OnFrame(const uint8_t *frame)
{
    const uint8_t *payload = &frame[LINK_OFF_PAYLOAD];
    uint8_t addr = frame[LINK_OFF_ADDR];
    uint8_t len  = frame[LINK_OFF_LEN];
    uint8_t cmd  = frame[LINK_OFF_CMD];
    uint8_t seq  = frame[LINK_OFF_SEQ];
    uint8_t reason;

    if ((addr != LINK_ADDR_LOCAL) && (addr != LINK_ADDR_BROADCAST))
    {
#ifdef LINK_DEBUG
        g_link_frame_other++;
#endif
        return;                                   /* meant for another node */
    }

    switch (cmd)
    {
    case LINK_CMD_CONTROL:
#ifdef LINK_DEBUG
        g_link_cmd_rx++;
#endif
        if (s_cmd_handler == NULL)
        {
            reason = LINK_NAK_UNSUPPORTED;
        }
        else
        {
            reason = s_cmd_handler(cmd, payload, len);
        }
        Link_SendAnswer(seq, cmd, reason);        /* a command is always answered */
        break;

    case LINK_CMD_QUERY:
        /* A query has to be answered with a data frame and not with an ACK.
           Nothing needs to be queried yet, so it is refused for now. */
        Link_SendAnswer(seq, cmd, LINK_NAK_UNSUPPORTED);
        break;

    case LINK_CMD_ACK:
        if ((s_tx_pend != 0U) && (seq == s_tx_pend_seq))
        {
            s_tx_pend = 0U;                       /* done, the SEQ is released   */
            s_tx_failed = 0U;
#ifdef LINK_DEBUG
            g_link_ack_rx++;
#endif
        }
        break;

    case LINK_CMD_NAK:
        if ((s_tx_pend != 0U) && (seq == s_tx_pend_seq))
        {
            s_tx_pend = 0U;                       /* refused, SEQ released again */
            s_tx_failed = 1U;
#ifdef LINK_DEBUG
            g_link_nak_rx++;
#endif
        }
        break;

    case LINK_CMD_REPORT:
    case LINK_CMD_HEARTBEAT:
    default:
        break;                                    /* never acknowledged */
    }
}

/**
 * @brief  Cut every complete frame out of the reassembly buffer.
 */
static void Link_ParserRun(void)
{
    while (s_asm_len > 0U)
    {
        uint16_t start = 0xFFFFU;
        uint16_t i;
        uint8_t  payload_len;
        uint16_t total;
        uint16_t crc_calc;
        uint16_t crc_recv;

        for (i = 0U; (uint16_t)(i + 1U) < s_asm_len; i++)
        {
            if ((s_asm_buf[i] == LINK_SOF0) && (s_asm_buf[i + 1U] == LINK_SOF1))
            {
                start = i;
                break;
            }
        }
        if (start == 0xFFFFU)
        {
            /* No header left, but keep the last byte, it may be a lone 0xAA. */
            s_asm_buf[0] = s_asm_buf[s_asm_len - 1U];
            s_asm_len = 1U;
            return;
        }
        if (start > 0U)
        {
            memmove(s_asm_buf, &s_asm_buf[start], (size_t)(s_asm_len - start));
            s_asm_len = (uint16_t)(s_asm_len - start);
        }
        if (s_asm_len < LINK_HDR_LEN)
        {
            return;                               /* header still incomplete */
        }
        payload_len = s_asm_buf[LINK_OFF_LEN];
        if (payload_len > LINK_MAX_PAYLOAD)
        {
#ifdef LINK_DEBUG
            g_link_frame_bad++;
#endif
            memmove(s_asm_buf, &s_asm_buf[1], (size_t)(s_asm_len - 1U));
            s_asm_len--;
            continue;                             /* resync on the next 0xAA 55 */
        }
        total = (uint16_t)(LINK_HDR_LEN + payload_len + LINK_CRC_LEN);
        if (s_asm_len < total)
        {
            return;                               /* body still incomplete */
        }
        crc_calc = Link_Crc16(&s_asm_buf[LINK_OFF_VER],
                              (uint16_t)((LINK_HDR_LEN - LINK_OFF_VER) + payload_len));
        crc_recv = (uint16_t)((uint16_t)s_asm_buf[total - 2U] |
                              ((uint16_t)s_asm_buf[total - 1U] << 8));
        if ((s_asm_buf[LINK_OFF_VER] != LINK_VER) || (crc_calc != crc_recv))
        {
#ifdef LINK_DEBUG
            g_link_frame_bad++;
#endif
        }
        else
        {
#ifdef LINK_DEBUG
            g_link_frame_ok++;
#endif
            Link_OnFrame(s_asm_buf);
        }
        memmove(s_asm_buf, &s_asm_buf[total], (size_t)(s_asm_len - total));
        s_asm_len = (uint16_t)(s_asm_len - total);
    }
}

/**
 * @brief  Append freshly received bytes and parse everything that is complete.
 * @param  data: new bytes.
 * @param  n:    number of new bytes.
 */
static void Link_ParserFeed(const uint8_t *data, uint16_t n)
{
    if (((uint32_t)n + (uint32_t)s_asm_len) > (uint32_t)sizeof(s_asm_buf))
    {
        s_asm_len = 0U;                           /* must not happen, start over */
    }
    memcpy(&s_asm_buf[s_asm_len], data, n);
    s_asm_len = (uint16_t)(s_asm_len + n);
    Link_ParserRun();
}

/**
 * @brief  Resend or give up the pending acknowledged transaction.
 * @param  now: current tick, HAL_GetTick().
 */
static void Link_TxTick(uint32_t now)
{
    if (s_tx_pend == 0U)
    {
        return;
    }
    if ((int32_t)(now - s_tx_deadline) < 0)
    {
        return;                                   /* still inside the timeout */
    }
    if (s_tx_retry < LINK_ACK_RETRY)
    {
        s_tx_retry++;
        s_tx_deadline = now + LINK_ACK_TIMEOUT_MS;
        (void)Link_SendFrame(s_tx_pend_cmd, s_tx_pend_seq, s_tx_pend_payload, s_tx_pend_len);
#ifdef LINK_DEBUG
        g_link_retry_tx++;
#endif
        return;
    }
    /* Answer lost: mark the transaction as failed and release the SEQ. */
    s_tx_pend = 0U;
    s_tx_failed = 1U;
#ifdef LINK_DEBUG
    g_link_timeout_tx++;
#endif
}

/**
 * @brief  Reset the link state and start reception.
 */
void Link_Init(void)
{
    s_tx_seq = 0U;
    s_tx_pend = 0U;
    s_tx_failed = 0U;
    s_tx_retry = 0U;
    s_asm_len = 0U;
    s_rx_idle = 0U;
    s_cmd_handler = NULL;
    Link_RxStart();
}

/**
 * @brief  USART2 interrupt hook, called first inside USART2_IRQHandler().
 * @note   It only records that a frame ends on the wire. The frame itself is
 *         parsed and answered later in Link_Poll(), so the ISR stays short and
 *         never performs a blocking transmit.
 */
void Link_OnUartIrq(void)
{
    uint32_t sr = huart2.Instance->SR;

#ifdef LINK_DEBUG
    if ((sr & (USART_SR_ORE | USART_SR_NE | USART_SR_FE | USART_SR_PE)) != 0U)
    {
        g_link_uart_err++;                        /* cleared by the DR read below */
    }
#endif
    if ((sr & USART_SR_IDLE) != 0U)
    {
        (void)huart2.Instance->DR;                /* SR + DR read clears IDLE */
        s_rx_idle = 1U;
#ifdef LINK_DEBUG
        g_link_idle_evt++;
#endif
    }
}

/**
 * @brief  Serve the link once, call it from the main loop.
 */
void Link_Poll(void)
{
    uint8_t  chunk[LINK_RX_CHUNK];
    uint16_t n;

    if (s_rx_idle != 0U)
    {
        /* The line just went idle, so a whole frame is waiting in the ring. */
        s_rx_idle = 0U;
        while ((n = Link_RxTake(chunk, (uint16_t)sizeof(chunk))) > 0U)
        {
            Link_ParserFeed(chunk, n);
        }
    }
    Link_TxTick(HAL_GetTick());
}

/**
 * @brief  Install the command handler.
 * @param  handler: handler for CONTROL frames, NULL disables the support.
 */
void Link_SetCmdHandler(Link_CmdHandler_t handler)
{
    s_cmd_handler = handler;
}

/**
 * @brief  Report a list of data items to the gateway.
 * @param  items: data item array.
 * @param  count: number of items.
 * @retval LINK_RET_OK or LINK_RET_FAIL.
 */
uint8_t Link_SendReport(const Link_Item_t *items, uint8_t count)
{
    uint8_t i;
    uint8_t n = 0U;

    if ((items == NULL) || (count == 0U))
    {
        return LINK_RET_FAIL;
    }
    if (((uint16_t)count * LINK_ITEM_LEN) > LINK_MAX_PAYLOAD)
    {
        return LINK_RET_FAIL;
    }
    for (i = 0U; i < count; i++)
    {
        s_report_payload[n] = items[i].id;
        n++;
        s_report_payload[n] = (uint8_t)((uint32_t)items[i].value & 0xFFU);
        n++;
        s_report_payload[n] = (uint8_t)(((uint32_t)items[i].value >> 8) & 0xFFU);
        n++;
        s_report_payload[n] = (uint8_t)(((uint32_t)items[i].value >> 16) & 0xFFU);
        n++;
        s_report_payload[n] = (uint8_t)(((uint32_t)items[i].value >> 24) & 0xFFU);
        n++;
    }
    return Link_SendFrame(LINK_CMD_REPORT, s_tx_seq++, s_report_payload, n);
}

/**
 * @brief  Send one heartbeat frame.
 * @retval LINK_RET_OK or LINK_RET_FAIL.
 */
uint8_t Link_SendHeartbeat(void)
{
    return Link_SendFrame(LINK_CMD_HEARTBEAT, s_tx_seq++, NULL, 0U);
}

/**
 * @brief  Send a frame that must be acknowledged (stop and wait).
 * @param  cmd:     command code.
 * @param  payload: payload bytes, may be NULL when len is 0.
 * @param  len:     payload length in bytes.
 * @retval LINK_RET_OK, LINK_RET_BUSY or LINK_RET_FAIL.
 */
uint8_t Link_SendReliable(uint8_t cmd, const uint8_t *payload, uint8_t len)
{
    uint8_t ret;

    if (s_tx_pend != 0U)
    {
        return LINK_RET_BUSY;                     /* one transaction at a time */
    }
    if (len > LINK_MAX_PAYLOAD)
    {
        return LINK_RET_FAIL;
    }
    if ((len > 0U) && (payload == NULL))
    {
        return LINK_RET_FAIL;
    }
    if (len > 0U)
    {
        memcpy(s_tx_pend_payload, payload, len);
    }
    s_tx_pend_len = len;
    s_tx_pend_cmd = cmd;
    s_tx_pend_seq = s_tx_seq;
    s_tx_seq++;
    ret = Link_SendFrame(cmd, s_tx_pend_seq, s_tx_pend_payload, len);
    if (ret != LINK_RET_OK)
    {
        return ret;                               /* nothing left the port */
    }
    s_tx_retry = 0U;
    s_tx_deadline = HAL_GetTick() + LINK_ACK_TIMEOUT_MS;
    s_tx_pend = 1U;
    return LINK_RET_OK;
}

/**
 * @brief  Tell whether an acknowledged transaction is still in flight.
 * @retval 1 when busy, 0 when free.
 */
uint8_t Link_TxBusy(void)
{
    return (s_tx_pend != 0U) ? 1U : 0U;
}

/**
 * @brief  Result of the last acknowledged transaction.
 * @retval 1 when it timed out, 0 when it was confirmed.
 */
uint8_t Link_LastTxFailed(void)
{
    return s_tx_failed;
}

#ifdef LINK_DEBUG
/**
 * @brief  Print every debug counter on USART1, call it as slow as you like.
 */
void Link_DumpStats(void)
{
    printf("[STAT] rx=%lu drop=%lu idle=%lu uerr=%lu | frm ok=%lu bad=%lu other=%lu\r\n",
           (unsigned long)g_link_rx_bytes, (unsigned long)g_link_rx_drop,
           (unsigned long)g_link_idle_evt, (unsigned long)g_link_uart_err,
           (unsigned long)g_link_frame_ok, (unsigned long)g_link_frame_bad,
           (unsigned long)g_link_frame_other);
    printf("[STAT] cmd=%lu ack_tx=%lu nak_tx=%lu ack_rx=%lu nak_rx=%lu retry=%lu timeout=%lu\r\n",
           (unsigned long)g_link_cmd_rx, (unsigned long)g_link_ack_tx,
           (unsigned long)g_link_nak_tx, (unsigned long)g_link_ack_rx,
           (unsigned long)g_link_nak_rx, (unsigned long)g_link_retry_tx,
           (unsigned long)g_link_timeout_tx);
}
#endif /* LINK_DEBUG */
