/**
  ******************************************************************************
  * @file    sen_soil.c
  * @brief   Implementation of the soil moisture driver.
  * @note    All this file does is average a handful of conversions and place the
  *          result between the two points the header was given.
  ******************************************************************************
  */
#include "sen_soil.h"
#include "bsp_delay.h"
#include <stdio.h>

/* ADC1 handle generated by CubeMX (defined in main.c). */
extern ADC_HandleTypeDef hadc1;

/**
 * @brief  Place a raw count between the dry point and the wet point.
 * @note   Written with the pair as given, so it comes out right whether this probe
 *         reads high when dry or high when wet: the sign of the divisor carries
 *         the direction.
 * @param  raw: the averaged count.
 * @retval the moisture, 0 .. 10000.
 */
static int32_t Sen_Soil_Map(uint32_t raw)
{
    int32_t dry = (int32_t)SEN_SOIL_RAW_DRY;
    int32_t wet = (int32_t)SEN_SOIL_RAW_WET;
    int32_t value;

    if (dry == wet)
    {
        return 0;                    /* nothing to interpolate between */
    }

    value = ((dry - (int32_t)raw) * 10000) / (dry - wet);

    if (value < 0)
    {
        value = 0;                   /* drier than the air it was set in */
    }
    if (value > 10000)
    {
        value = 10000;               /* wetter than the water it was set in */
    }

    return value;
}

/**
 * @brief  Feed the module or cut it off.
 * @param  on: 0 cuts the probe off, anything else feeds it.
 */
static void Sen_Soil_Power(uint8_t on)
{
    HAL_GPIO_WritePin(SEN_SOIL_PWR_PORT, SEN_SOIL_PWR_PIN,
                      (on != 0U) ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/**
 * @brief  Set the sampling window and calibrate the ADC, and take charge of the
 *         pin that feeds the module.
 * @retval 0 on success, 1 on failure.
 */
uint8_t Sen_Soil_Init(void)
{
    ADC_ChannelConfTypeDef cfg = {0};
    GPIO_InitTypeDef       gpio = {0};

    if (SEN_SOIL_ADC.Instance != ADC1)
    {
        return 1U;                       /* CubeMX never brought ADC1 up */
    }

    /* Cut the probe off before anything else, whatever the generated file left
       the pin at. An unpowered probe is the whole point of this driver, so it must
       not depend on the order two initialisations happen to run in. */
    SEN_SOIL_PWR_CLK_ENABLE();
    Sen_Soil_Power(0U);

    /* Applied here rather than left to the generated file, the same way the DHT22
       driver fixes up its own pin, so a regeneration that resets it costs nothing
       but a rebuild. */
    gpio.Pin = SEN_SOIL_PWR_PIN;
    gpio.Mode = GPIO_MODE_OUTPUT_PP;
    gpio.Pull = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(SEN_SOIL_PWR_PORT, &gpio);

    cfg.Channel = SEN_SOIL_CHANNEL;
    cfg.Rank = ADC_REGULAR_RANK_1;
    cfg.SamplingTime = SEN_SOIL_SAMPLE_TIME;
    if (HAL_ADC_ConfigChannel(&SEN_SOIL_ADC, &cfg) != HAL_OK)
    {
        return 1U;
    }

    /* An F1 wants one calibration after the ADC comes up, or the first readings
       are off by more than the probe is worth. This one touches ADC1 only, so the
       light sensor on ADC3 is left alone. */
    if (HAL_ADCEx_Calibration_Start(&SEN_SOIL_ADC) != HAL_OK)
    {
        return 1U;
    }

    return 0U;
}

/**
 * @brief  Read the probe once.
 * @param  moisture_x100: destination of the moisture, 0 .. 10000.
 * @retval 0 on success, 1 on failure.
 */
uint8_t Sen_Soil_Read(int32_t *moisture_x100)
{
    uint32_t sum = 0U;
    uint32_t raw;
    uint8_t  i;
    uint8_t  failed = 0U;

    if (moisture_x100 == NULL)
    {
        return 1U;
    }

    /* Feed the module, give it a moment, measure, then cut it off again.
       One conversion per call: the ADC was set up to convert once on a software
       trigger, which is what keeps this a plain poll with no interrupt and no DMA
       behind it. */
    Sen_Soil_Power(1U);
    BSP_Delay_Ms(SEN_SOIL_SETTLE_MS);

    for (i = 0U; i < (uint8_t)SEN_SOIL_SAMPLES; i++)
    {
        if (HAL_ADC_Start(&SEN_SOIL_ADC) != HAL_OK)
        {
            failed = 1U;
            break;
        }
        if (HAL_ADC_PollForConversion(&SEN_SOIL_ADC,
                                      (uint32_t)SEN_SOIL_TIMEOUT_MS) != HAL_OK)
        {
            failed = 1U;
            break;
        }
        sum += HAL_ADC_GetValue(&SEN_SOIL_ADC);
    }

    /* The single way out of the measuring section, so that no path above can
       leave the probe energised: a probe still fed because a conversion timed out
       would quietly undo the whole reason this driver exists. */
    (void)HAL_ADC_Stop(&SEN_SOIL_ADC);
    Sen_Soil_Power(0U);

    if (failed != 0U)
    {
        return 1U;
    }

    raw = sum / (uint32_t)SEN_SOIL_SAMPLES;
    *moisture_x100 = Sen_Soil_Map(raw);

#if (SEN_SOIL_TRACE != 0)
    /* The calibration aid of the header, and the only reason this file mentions
       the console. It goes away with the switch. */
    printf("[SOIL] raw %d -> %d.%02d %%\r\n",
           (int)raw,
           (int)(*moisture_x100 / 100),
           (int)(*moisture_x100 % 100));
#endif

    return 0U;
}

/**
 * @brief  Device layer entry: hand out DEV_CH_SOIL.
 * @param  out:        buffer that receives the value.
 * @param  max_values: capacity of that buffer.
 * @retval number of values written, 0 when the read failed.
 */
uint8_t Sen_Soil_Sample(Dev_Value_t *out, uint8_t max_values)
{
    int32_t moisture_x100 = 0;

    if ((out == NULL) || (max_values < 1U))
    {
        return 0U;
    }
    if (Sen_Soil_Read(&moisture_x100) != 0U)
    {
        return 0U;
    }
    out[0].ch = DEV_CH_SOIL;
    out[0].value = moisture_x100;

    return 1U;
}

/* The instance that Dev_Manager registers in its sensor array. */
const Dev_Sensor_t g_sen_soil =
{
    "SOIL",
    Sen_Soil_Init,
    Sen_Soil_Sample
};
