/**
  ******************************************************************************
  * @file    sen_soil.c
  * @brief   Implementation of the soil moisture driver.
  * @note    All this file does is average a handful of conversions and place the
  *          result between the two points the header was given.
  ******************************************************************************
  */
#include "sen_soil.h"
#include <stdio.h>

/* ADC1 handle generated by CubeMX (defined in main.c). */
extern ADC_HandleTypeDef hadc1;

/**
 * @brief  Place a raw count between the dry point and the wet point.
 * @note   Written with the pair as given, so it comes out right whether this probe
 *         reads high when dry or high when wet: the sign of the divisor carries
 *         the direction.
 * @param  raw: the averaged count.
 * @retval the moisture, 0 .. 10000.
 */
static int32_t Sen_Soil_Map(uint32_t raw)
{
    int32_t dry = (int32_t)SEN_SOIL_RAW_DRY;
    int32_t wet = (int32_t)SEN_SOIL_RAW_WET;
    int32_t value;

    if (dry == wet)
    {
        return 0;                    /* nothing to interpolate between */
    }

    value = ((dry - (int32_t)raw) * 10000) / (dry - wet);

    if (value < 0)
    {
        value = 0;                   /* drier than the air it was set in */
    }
    if (value > 10000)
    {
        value = 10000;               /* wetter than the water it was set in */
    }

    return value;
}

/**
 * @brief  Set the sampling window and calibrate the ADC.
 * @retval 0 on success, 1 on failure.
 */
uint8_t Sen_Soil_Init(void)
{
    ADC_ChannelConfTypeDef cfg = {0};

    if (SEN_SOIL_ADC.Instance != ADC1)
    {
        return 1U;                       /* CubeMX never brought ADC1 up */
    }

    cfg.Channel = SEN_SOIL_CHANNEL;
    cfg.Rank = ADC_REGULAR_RANK_1;
    cfg.SamplingTime = SEN_SOIL_SAMPLE_TIME;
    if (HAL_ADC_ConfigChannel(&SEN_SOIL_ADC, &cfg) != HAL_OK)
    {
        return 1U;
    }

    /* An F1 wants one calibration after the ADC comes up, or the first readings
       are off by more than the probe is worth. This one touches ADC1 only, so the
       light sensor on ADC3 is left alone. */
    if (HAL_ADCEx_Calibration_Start(&SEN_SOIL_ADC) != HAL_OK)
    {
        return 1U;
    }

    return 0U;
}

/**
 * @brief  Read the probe once.
 * @param  moisture_x100: destination of the moisture, 0 .. 10000.
 * @retval 0 on success, 1 on failure.
 */
uint8_t Sen_Soil_Read(int32_t *moisture_x100)
{
    uint32_t sum = 0U;
    uint32_t raw;
    uint8_t  i;

    if (moisture_x100 == NULL)
    {
        return 1U;
    }

    /* One conversion per call: the ADC was set up to convert once on a software
       trigger, which is what keeps this a plain poll with no interrupt and no
       DMA behind it. */
    for (i = 0U; i < (uint8_t)SEN_SOIL_SAMPLES; i++)
    {
        if (HAL_ADC_Start(&SEN_SOIL_ADC) != HAL_OK)
        {
            (void)HAL_ADC_Stop(&SEN_SOIL_ADC);
            return 1U;
        }
        if (HAL_ADC_PollForConversion(&SEN_SOIL_ADC,
                                      (uint32_t)SEN_SOIL_TIMEOUT_MS) != HAL_OK)
        {
            (void)HAL_ADC_Stop(&SEN_SOIL_ADC);
            return 1U;
        }
        sum += HAL_ADC_GetValue(&SEN_SOIL_ADC);
    }
    (void)HAL_ADC_Stop(&SEN_SOIL_ADC);

    raw = sum / (uint32_t)SEN_SOIL_SAMPLES;
    *moisture_x100 = Sen_Soil_Map(raw);

#if (SEN_SOIL_TRACE != 0)
    /* The calibration aid of the header, and the only reason this file mentions
       the console. It goes away with the switch. */
    printf("[SOIL] raw %d -> %d.%02d %%\r\n",
           (int)raw,
           (int)(*moisture_x100 / 100),
           (int)(*moisture_x100 % 100));
#endif

    return 0U;
}

/**
 * @brief  Device layer entry: hand out DEV_CH_SOIL.
 * @param  out:        buffer that receives the value.
 * @param  max_values: capacity of that buffer.
 * @retval number of values written, 0 when the read failed.
 */
uint8_t Sen_Soil_Sample(Dev_Value_t *out, uint8_t max_values)
{
    int32_t moisture_x100 = 0;

    if ((out == NULL) || (max_values < 1U))
    {
        return 0U;
    }
    if (Sen_Soil_Read(&moisture_x100) != 0U)
    {
        return 0U;
    }
    out[0].ch = DEV_CH_SOIL;
    out[0].value = moisture_x100;

    return 1U;
}

/* The instance that Dev_Manager registers in its sensor array. */
const Dev_Sensor_t g_sen_soil =
{
    "SOIL",
    Sen_Soil_Init,
    Sen_Soil_Sample
};
