/**
  ******************************************************************************
  * @file    sen_light.c
  * @brief   Implementation of the light sensor driver.
  * @note    The ADC does the measuring. All this file does is average a handful
  *          of conversions and turn the result into a share of the reference.
  ******************************************************************************
  */
#include "sen_light.h"

/* ADC3 handle generated by CubeMX (defined in main.c). */
extern ADC_HandleTypeDef hadc3;

/**
 * @brief  Set the sampling window and calibrate the ADC.
 * @retval 0 on success, 1 on failure.
 */
uint8_t Sen_Light_Init(void)
{
    ADC_ChannelConfTypeDef cfg = {0};

    if (SEN_LIGHT_ADC.Instance != ADC3)
    {
        return 1U;                       /* CubeMX never brought ADC3 up */
    }

    cfg.Channel = SEN_LIGHT_CHANNEL;
    cfg.Rank = ADC_REGULAR_RANK_1;
    cfg.SamplingTime = SEN_LIGHT_SAMPLE_TIME;
    if (HAL_ADC_ConfigChannel(&SEN_LIGHT_ADC, &cfg) != HAL_OK)
    {
        return 1U;
    }

    /* An F1 wants one calibration after the ADC comes up, or the first readings
       are off by more than the sensor is worth. */
    if (HAL_ADCEx_Calibration_Start(&SEN_LIGHT_ADC) != HAL_OK)
    {
        return 1U;
    }

    return 0U;
}

/**
 * @brief  Read the sensor once.
 * @param  level_x100: destination of the brightness, 0 .. 10000.
 * @retval 0 on success, 1 on failure.
 */
uint8_t Sen_Light_Read(int32_t *level_x100)
{
    uint32_t sum = 0U;
    uint32_t raw;
    uint8_t  i;

    if (level_x100 == NULL)
    {
        return 1U;
    }

    /* One conversion per call: the ADC was set up to convert once on a software
       trigger, which is what keeps this a plain poll with no interrupt and no
       DMA behind it. */
    for (i = 0U; i < (uint8_t)SEN_LIGHT_SAMPLES; i++)
    {
        if (HAL_ADC_Start(&SEN_LIGHT_ADC) != HAL_OK)
        {
            (void)HAL_ADC_Stop(&SEN_LIGHT_ADC);
            return 1U;
        }
        if (HAL_ADC_PollForConversion(&SEN_LIGHT_ADC,
                                      (uint32_t)SEN_LIGHT_TIMEOUT_MS) != HAL_OK)
        {
            (void)HAL_ADC_Stop(&SEN_LIGHT_ADC);
            return 1U;
        }
        sum += HAL_ADC_GetValue(&SEN_LIGHT_ADC);
    }
    (void)HAL_ADC_Stop(&SEN_LIGHT_ADC);

    raw = sum / (uint32_t)SEN_LIGHT_SAMPLES;

#if (SEN_LIGHT_INVERT != 0)
    raw = (uint32_t)SEN_LIGHT_FULL_SCALE - raw;
#endif

    /* Scaled by 100 like every other value of the project, see dev_manager.h. */
    *level_x100 = (int32_t)((raw * 10000U) / (uint32_t)SEN_LIGHT_FULL_SCALE);
    return 0U;
}

/**
 * @brief  Device layer entry: hand out DEV_CH_LIGHT.
 * @param  out:        buffer that receives the value.
 * @param  max_values: capacity of that buffer.
 * @retval number of values written, 0 when the read failed.
 */
uint8_t Sen_Light_Sample(Dev_Value_t *out, uint8_t max_values)
{
    int32_t level_x100 = 0;

    if ((out == NULL) || (max_values < 1U))
    {
        return 0U;
    }
    if (Sen_Light_Read(&level_x100) != 0U)
    {
        return 0U;
    }
    out[0].ch = DEV_CH_LIGHT;
    out[0].value = level_x100;

    return 1U;
}

/* The instance that Dev_Manager registers in its sensor array. */
const Dev_Sensor_t g_sen_light =
{
    "LIGHT",
    Sen_Light_Init,
    Sen_Light_Sample
};
