/**
  ******************************************************************************
  * @file    sen_co2.c
  * @brief   Implementation of the JW01 CO2 driver.
  * @note    Reception is a DMA ring read by hand rather than through
  *          HAL_UART_Receive_DMA(), for the reason bsp_uart.c gives about the
  *          gateway link: that call gives up on the first overrun or framing
  *          error and would leave the sensor unread until the next reset. This
  *          module talks on its own, so a silence of that kind would look
  *          exactly like a sensor that had been unplugged.
  ******************************************************************************
  */
#include "sen_co2.h"
#include <stdio.h>

/* USART3 and its RX DMA channel are generated by CubeMX and defined in main.c. */
extern UART_HandleTypeDef huart3;
extern DMA_HandleTypeDef  hdma_usart3_rx;

static uint8_t  s_rx_buf[SEN_CO2_RX_BUF_SIZE];  /* filled by the DMA, wraps   */
static uint16_t s_rx_tail;                      /* oldest byte still unread   */

/* The last six bytes seen, kept as a little ring so that a frame split across
   two polls still lines up. Once it is full, s_win_at is the oldest of the six
   and the newest sits just behind it. */
static uint8_t s_win[SEN_CO2_FRAME_LEN];
static uint8_t s_win_at;
static uint8_t s_win_len;

static uint8_t  s_have_frame;
static int32_t  s_last_ppm;
static uint32_t s_last_frame_ms;
static uint32_t s_start_ms;

/* One byte of the window, oldest first. */
#define SEN_CO2_WIN(k)  \
    s_win[(uint8_t)(((uint32_t)s_win_at + (uint32_t)(k)) % (uint32_t)SEN_CO2_FRAME_LEN)]

/**
 * @brief  Add one byte to the window and test it for a frame.
 * @param  b: the byte just received.
 */
static void Sen_Co2_Push(uint8_t b)
{
    uint8_t  sum = 0U;
    uint8_t  j;
    uint32_t ppm;

    s_win[s_win_at] = b;
    s_win_at = (uint8_t)((s_win_at + 1U) % (uint8_t)SEN_CO2_FRAME_LEN);

    if (s_win_len < (uint8_t)SEN_CO2_FRAME_LEN)
    {
        s_win_len++;
        if (s_win_len < (uint8_t)SEN_CO2_FRAME_LEN)
        {
            return;                     /* not six bytes of window yet */
        }
    }

    if (SEN_CO2_WIN(0U) != (uint8_t)SEN_CO2_ADDR)
    {
        return;                         /* not where a frame can start */
    }
    for (j = 0U; j < (uint8_t)(SEN_CO2_FRAME_LEN - 1U); j++)
    {
        sum = (uint8_t)(sum + SEN_CO2_WIN(j));
    }
    if (sum != SEN_CO2_WIN((uint8_t)(SEN_CO2_FRAME_LEN - 1U)))
    {
        return;                         /* the sum disagrees, so it is noise */
    }

    ppm = ((uint32_t)SEN_CO2_WIN(1U) << 8) | (uint32_t)SEN_CO2_WIN(2U);

    s_last_ppm = (int32_t)ppm;
    s_last_frame_ms = HAL_GetTick();
    s_have_frame = 1U;

#if (SEN_CO2_TRACE != 0)
    /* The bring up aid of the header, and the only reason this file mentions the
       console. It goes away with the switch. */
    printf("[CO2 ] %02X %02X %02X %02X %02X %02X -> %u ppm\r\n",
           (unsigned)SEN_CO2_WIN(0U), (unsigned)SEN_CO2_WIN(1U),
           (unsigned)SEN_CO2_WIN(2U), (unsigned)SEN_CO2_WIN(3U),
           (unsigned)SEN_CO2_WIN(4U), (unsigned)SEN_CO2_WIN(5U),
           (unsigned)ppm);
#endif
}

/**
 * @brief  Feed the window with whatever arrived since the last call.
 */
static void Sen_Co2_Poll(void)
{
    uint16_t head = (uint16_t)((uint16_t)SEN_CO2_RX_BUF_SIZE -
                               (uint16_t)__HAL_DMA_GET_COUNTER(&hdma_usart3_rx));
    uint16_t n;
    uint16_t i;

    n = (head >= s_rx_tail) ? (uint16_t)(head - s_rx_tail)
                            : (uint16_t)((uint16_t)SEN_CO2_RX_BUF_SIZE - s_rx_tail + head);
    if (n == 0U)
    {
        return;
    }

    /* Walked straight out of the ring rather than copied out first: the window
       only wants one byte at a time, and a scratch buffer of the ring's size
       would be a quarter of a kilobyte of stack for nothing. */
    for (i = 0U; i < n; i++)
    {
        Sen_Co2_Push(s_rx_buf[(uint16_t)(((uint32_t)s_rx_tail + (uint32_t)i) %
                                         (uint32_t)SEN_CO2_RX_BUF_SIZE)]);
    }
    s_rx_tail = head;
}

/**
 * @brief  Arm the DMA ring.
 * @retval 0 on success, 1 on failure.
 */
uint8_t Sen_Co2_Init(void)
{
    if (SEN_CO2_UART.Instance != USART3)
    {
        return 1U;                       /* CubeMX never brought USART3 up */
    }

    /* Pointers and enable bits by hand, the way bsp_uart.c arms the gateway
       ring, and HAL kept out of the receive path. */
    __HAL_DMA_DISABLE(&hdma_usart3_rx);
    hdma_usart3_rx.Instance->CPAR  = (uint32_t)&SEN_CO2_UART.Instance->DR;
    hdma_usart3_rx.Instance->CMAR  = (uint32_t)s_rx_buf;
    hdma_usart3_rx.Instance->CNDTR = (uint32_t)SEN_CO2_RX_BUF_SIZE;

    s_rx_tail = 0U;
    s_win_at = 0U;
    s_win_len = 0U;
    s_have_frame = 0U;
    s_last_ppm = 0;
    s_last_frame_ms = 0U;
    s_start_ms = HAL_GetTick();

    __HAL_DMA_ENABLE(&hdma_usart3_rx);
    SET_BIT(SEN_CO2_UART.Instance->CR3, USART_CR3_DMAR);   /* UART asks the DMA */

    return 0U;
}

/**
 * @brief  Report the most recent reading.
 * @param  ppm: destination, parts per million.
 * @retval 0 on success, 1 when there is nothing current to report.
 */
uint8_t Sen_Co2_Read(int32_t *ppm)
{
    uint32_t now;

    if (ppm == NULL)
    {
        return 1U;
    }

    Sen_Co2_Poll();

    now = HAL_GetTick();

    if ((uint32_t)(now - s_start_ms) < (uint32_t)SEN_CO2_WARMUP_MS)
    {
        return 1U;                       /* still warming up, see the header */
    }
    if ((s_have_frame == 0U) ||
        ((uint32_t)(now - s_last_frame_ms) > (uint32_t)SEN_CO2_STALE_MS))
    {
        return 1U;                       /* nothing yet, or nothing recent */
    }

    *ppm = s_last_ppm;
    return 0U;
}

/**
 * @brief  Device layer entry: hand out DEV_CH_CO2.
 * @param  out:        buffer that receives the value.
 * @param  max_values: capacity of that buffer.
 * @retval number of values written, 0 when the read failed.
 */
uint8_t Sen_Co2_Sample(Dev_Value_t *out, uint8_t max_values)
{
    int32_t ppm = 0;

    if ((out == NULL) || (max_values < 1U))
    {
        return 0U;
    }
    if (Sen_Co2_Read(&ppm) != 0U)
    {
        return 0U;
    }
    out[0].ch = DEV_CH_CO2;
    out[0].value = ppm * 100;            /* the project's scale, dev_manager.h */

    return 1U;
}

/* The instance that Dev_Manager registers in its sensor array. */
const Dev_Sensor_t g_sen_co2 =
{
    "CO2",
    Sen_Co2_Init,
    Sen_Co2_Sample
};
